name: CD

on:
  push:
    branches:
      - main

jobs:
  release:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Examples
        run: npm run build:examples

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: >
          npx 
          -p semantic-release@19
          -p @semantic-release/changelog@6
          -p @semantic-release/exec@6
          -p @semantic-release/git@10
          semantic-release

      - name: Deploy My React Crasher 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          repository-name: BugSplat-Git/bugsplat-git.github.io
          branch: gh-pages
          folder: examples/my-react-crasher/dist
          target-folder: my-react-crasher
          token: ${{ secrets.GH_TOKEN }}
